package FilesApp;


import java.io.IOException;

/**
* FilesApp/FilesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* 7 �������� 2019 �. 11:47:44 GMT+06:00
*/

public abstract class FilesPOA extends org.omg.PortableServer.Servant
 implements FilesApp.FilesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<String, Integer>();
  static
  {
    _methods.put ("connectFiles", 0);
    _methods.put ("shutdown", 1);
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = _methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method)
    {
       case 0:  // FilesApp/Files/connectFiles
       {
         try {
           this.connectFiles ();
         } catch (IOException e) {
           e.printStackTrace();
         }
         out = $rh.createReply();
         break;
       }

       case 1:  // FilesApp/Files/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FilesApp/Files:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Files _this() 
  {
    return FilesHelper.narrow(
    super._this_object());
  }

  public Files _this(org.omg.CORBA.ORB orb) 
  {
    return FilesHelper.narrow(
    super._this_object(orb));
  }


} // class FilesPOA
