package FilesApp;

/**
* FilesApp/FilesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* 7 сент€бр€ 2019 г. 11:47:44 GMT+06:00
*/

public final class FilesHolder implements org.omg.CORBA.portable.Streamable
{
  public FilesApp.Files value = null;

  public FilesHolder ()
  {
  }

  public FilesHolder (FilesApp.Files initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FilesApp.FilesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FilesApp.FilesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FilesApp.FilesHelper.type ();
  }

}
