package FilesApp;


import java.io.IOException;

/**
* FilesApp/FilesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* 7 �������� 2019 �. 11:47:44 GMT+06:00
*/

public interface FilesOperations 
{
  void connectFiles () throws IOException;
  void shutdown ();
} // interface FilesOperations
