package FilesApp;


/**
* FilesApp/Files.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* 7 сент€бр€ 2019 г. 11:47:44 GMT+06:00
*/

public interface Files extends FilesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Files
