package kr1.NumberApp;


/**
* NumberApp/Numbers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/App.idl
* 21 �������� 2019 �. 13:41:44 GMT+06:00
*/

public interface Numbers extends NumbersOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Numbers
