package kr1.NumberApp;


/**
* NumberApp/NumbersPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/App.idl
* 21 �������� 2019 �. 13:41:43 GMT+06:00
*/

public abstract class NumbersPOA extends org.omg.PortableServer.Servant
 implements NumbersOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<>();
  static
  {
    _methods.put ("numbersMap", 0);
    _methods.put ("shutdown", 1);
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = _methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method)
    {
       case 0:  // NumberApp/Numbers/numbersMap
       {
         int $result[] = null;
         $result = this.numbersMap ();
         out = $rh.createReply();
         numberListHelper.write (out, $result);
         break;
       }

       case 1:  // NumberApp/Numbers/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:NumberApp/Numbers:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Numbers _this() 
  {
    return NumbersHelper.narrow(
    super._this_object());
  }

  public Numbers _this(org.omg.CORBA.ORB orb) 
  {
    return NumbersHelper.narrow(
    super._this_object(orb));
  }


} // class NumbersPOA
