package kr1.NumberApp;


/**
* NumberApp/numberListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/App.idl
* 21 �������� 2019 �. 13:41:43 GMT+06:00
*/

public final class numberListHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public numberListHolder ()
  {
  }

  public numberListHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = numberListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    numberListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return numberListHelper.type ();
  }

}
