package kr1.NumberApp;


/**
* NumberApp/NumbersOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/App.idl
* 21 �������� 2019 �. 13:41:44 GMT+06:00
*/

public interface NumbersOperations 
{
  int[] numbersMap ();
  void shutdown ();
} // interface NumbersOperations
