package kr1.NumberApp;


/**
* NumberApp/NumbersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/App.idl
* 21 �������� 2019 �. 13:41:43 GMT+06:00
*/

abstract public class NumbersHelper
{
  private static String  _id = "IDL:NumberApp/Numbers:1.0";

  public static void insert (org.omg.CORBA.Any a, Numbers that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Numbers extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (NumbersHelper.id (), "Numbers");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Numbers read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NumbersStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Numbers value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Numbers narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Numbers)
      return (Numbers)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _NumbersStub stub = new _NumbersStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Numbers unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Numbers)
      return (Numbers)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _NumbersStub stub = new _NumbersStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
