package kr1.NumberApp;

/**
* NumberApp/NumbersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/App.idl
* 21 �������� 2019 �. 13:41:43 GMT+06:00
*/

public final class NumbersHolder implements org.omg.CORBA.portable.Streamable
{
  public Numbers value = null;

  public NumbersHolder ()
  {
  }

  public NumbersHolder (Numbers initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NumbersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NumbersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NumbersHelper.type ();
  }

}
